### ISSUE TITLE
Error: Failed parsing JSON config key this.mediatorName:

### ISSUE THREAD

**Issue by kiranatious** [majgis/psproxy#4]
when i type 

npm install psproxy in Mac Terminal (npm, node and others are installed)

i Get
Error: Failed parsing JSON config key this.mediatorName: "" + this.componentType + "-mediator"
    at parseField (/usr/local/lib/node_modules/npm/lib/config/core.js:379:13)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:335:17
    at Array.forEach (native)
    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:334:23)
    at ConfigChain.addString (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:322:10)
    at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)

**Comment by ghost** [comment]
This is the first time seeing this.  I no longer have a mac, so if you identify the issue feel free to create a PR.
